# Generated by Django 6.0.1 on 2026-03-02 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='name')),
                ('price', models.FloatField(verbose_name='price')),
                ('stock', models.IntegerField()),
                ('on_sale', models.BooleanField(default=False, verbose_name='on sale')),
            ],
        ),
    ]
